import { ArabicLetter } from "@/types";

export const ARABIC_VOWELS = [
  {
    id: "fatha",
    arabic: "\u0640\u064E",
    name: "Fatha",
    sound: "a",
    transcription: "a",
  },
  {
    id: "kasra",
    arabic: "\u0640\u0650",
    name: "Kasra",
    sound: "i",
    transcription: "i",
  },
  {
    id: "damma",
    arabic: "\u0640\u064F",
    name: "Damma",
    sound: "u",
    transcription: "u",
  },
  {
    id: "sukun",
    arabic: "\u0640\u0652",
    name: "Sukun",
    sound: "skip",
    transcription: "",
  }, // No vowel sound
];

export const ARABIC_LETTERS: ArabicLetter[] = [
  // Vowels moved to the beginning
  {
    id: "fatha",
    name: "Fatha",
    arabic: "ـَ",
    transliteration: "a",
    pronunciation: "Short 'a' sound (above letter)",
    forms: { isolated: "ـَ", initial: "ـَ", medial: "ـَ", final: "ـَ" },
    description:
      "A small diagonal line above a letter. Represents a short 'a' vowel.",
    connection: "right",
    type: "vowel",
  },
  {
    id: "kasra",
    name: "Kasra",
    arabic: "ـِ",
    transliteration: "i",
    pronunciation: "Short 'i' sound (below letter)",
    forms: { isolated: "ـِ", initial: "ـِ", medial: "ـِ", final: "ـِ" },
    description:
      "A small diagonal line below a letter. Represents a short 'i' vowel.",
    connection: "right",
    type: "vowel",
  },
  {
    id: "damma",
    name: "Damma",
    arabic: "ـُ",
    transliteration: "u",
    pronunciation: "Short 'u' sound (above letter)",
    forms: { isolated: "ـُ", initial: "ـُ", medial: "ـُ", final: "ـُ" },
    description:
      "A small loop (like a wow) above a letter. Represents a short 'u' vowel.",
    connection: "right",
    type: "vowel",
  },
  {
    id: "sukun",
    name: "Sukun",
    arabic: "ـْ",
    transliteration: "",
    pronunciation: "Absence of vowel (stop)",
    forms: { isolated: "ـْ", initial: "ـْ", medial: "ـْ", final: "ـْ" },
    description:
      "A small circle above a letter indicating no vowel sound follows.",
    connection: "right",
    type: "vowel",
  },
  {
    id: "fathatan",
    name: "Fathatan",
    arabic: "ـً",
    transliteration: "an",
    pronunciation: "'an' sound (usually on Alif)",
    forms: { isolated: "ـً", initial: "ـً", medial: "ـً", final: "ـً" },
    description:
      "Double Fatha. Makes an 'an' sound. Usually appears on an Alif at the end of a word.",
    connection: "right",
    type: "vowel",
  },
  {
    id: "kasratan",
    name: "Kasratan",
    arabic: "ـٍ",
    transliteration: "in",
    pronunciation: "'in' sound",
    forms: { isolated: "ـٍ", initial: "ـٍ", medial: "ـٍ", final: "ـٍ" },
    description: "Double Kasra. Makes an 'in' sound using below the letter.",
    connection: "right",
    type: "vowel",
  },
  {
    id: "dammatan",
    name: "Dammatan",
    arabic: "ـٌ",
    transliteration: "un",
    pronunciation: "'un' sound",
    forms: { isolated: "ـٌ", initial: "ـٌ", medial: "ـٌ", final: "ـٌ" },
    description: "Double Damma. Makes an 'un' sound.",
    connection: "right",
    type: "vowel",
  },
  {
    id: "shadda",
    name: "Shadda",
    arabic: "ـّ",
    transliteration: "",
    pronunciation: "Doubles the letter",
    forms: { isolated: "ـّ", initial: "ـّ", medial: "ـّ", final: "ـّ" },
    description:
      "A w-shaped sign above a letter. It emphasizes or doubles the consonant sound.",
    connection: "right",
    type: "vowel",
  },
  // Consonants
  {
    id: "alif",
    name: "Alif",
    arabic: "ا",
    transliteration: "ā",
    pronunciation: "Open 'a' sound like in 'father', or a glottal stop",
    forms: { isolated: "ا", initial: "ا", medial: "ـا", final: "ـا" },
    description:
      "Alif is the first letter. It is often a long vowel 'aa'. It is a 'selfish' letter, meaning it only connects to the right.",
    connection: "right",
    examples: [
      {
        word: "أَسَد",
        meaning: { en: "Lion", bs: "Lav" },
        position: "initial",
      },
      {
        word: "بَاب",
        meaning: { en: "Door", bs: "Vrata" },
        position: "medial",
      },
      {
        word: "عَصَا",
        meaning: { en: "Stick", bs: "Štap" },
        position: "final",
      },
    ],
  },
  {
    id: "ba",
    name: "Ba",
    arabic: "ب",
    transliteration: "b",
    pronunciation: "Like 'b' in 'bed'",
    forms: { isolated: "ب", initial: "بـ", medial: "ـبـ", final: "ـب" },
    description: "Ba has a dot below. It connects from both sides.",
    connection: "both",
    examples: [
      {
        word: "بَيْض",
        meaning: { en: "Eggs", bs: "Jaja" },
        position: "initial",
      },
      {
        word: "خُبْز",
        meaning: { en: "Bread", bs: "Hljeb" },
        position: "medial",
      },
      { word: "كَلْب", meaning: { en: "Dog", bs: "Pas" }, position: "final" },
    ],
  },
  {
    id: "ta",
    name: "Ta",
    arabic: "ت",
    transliteration: "t",
    pronunciation: "Like 't' in 'tea' (soft)",
    forms: { isolated: "ت", initial: "تـ", medial: "ـتـ", final: "ـت" },
    description: "Ta has two dots above. It connects from both sides.",
    connection: "both",
    examples: [
      {
        word: "تَمْر",
        meaning: { en: "Dates", bs: "Hurma" },
        position: "initial",
      },
      {
        word: "كِتَاب",
        meaning: { en: "Book", bs: "Knjiga" },
        position: "medial",
      },
      {
        word: "بَيْت",
        meaning: { en: "House", bs: "Kuća" },
        position: "final",
      },
    ],
  },
  {
    id: "tha",
    name: "Tha",
    arabic: "ث",
    transliteration: "th",
    pronunciation: "Like 'th' in 'three'",
    forms: { isolated: "ث", initial: "ثـ", medial: "ـثـ", final: "ـث" },
    description: "Tha has three dots above. It connects from both sides.",
    connection: "both",
    examples: [
      {
        word: "ثَعْلَب",
        meaning: { en: "Fox", bs: "Lisica" },
        position: "initial",
      },
      {
        word: "كُمِّثْرَى",
        meaning: { en: "Pear", bs: "Kruška" },
        position: "medial",
      },
      {
        word: "مُثَلَّث",
        meaning: { en: "Triangle", bs: "Trougao" },
        position: "final",
      },
    ],
  },
  {
    id: "jim",
    name: "Jim",
    arabic: "ج",
    transliteration: "j",
    pronunciation: "Like 'j' in 'jam'",
    forms: { isolated: "ج", initial: "جـ", medial: "ـجـ", final: "ـج" },
    description:
      "Jim has a dot inside (or below in initial/medial). Connects both sides.",
    connection: "both",
    examples: [
      {
        word: "جَمَل",
        meaning: { en: "Camel", bs: "Deva" },
        position: "initial",
      },
      {
        word: "شَجَرَة",
        meaning: { en: "Tree", bs: "Drvo" },
        position: "medial",
      },
      {
        word: "ثَلْج",
        meaning: { en: "Snow", bs: "Snijeg" },
        position: "final",
      },
    ],
  },
  {
    id: "ha",
    name: "Ha",
    arabic: "ح",
    transliteration: "ḥ",
    pronunciation: "Sharp 'h', from the throat. Like exhaling relief.",
    forms: { isolated: "ح", initial: "حـ", medial: "ـحـ", final: "ـح" },
    description: "Ha has no dots. Connects both sides.",
    connection: "both",
    examples: [
      {
        word: "حِصَان",
        meaning: { en: "Horse", bs: "Konj" },
        position: "initial",
      },
      { word: "بَحْر", meaning: { en: "Sea", bs: "More" }, position: "medial" },
      {
        word: "تِمْسَاح",
        meaning: { en: "Crocodile", bs: "Krokodil" },
        position: "final",
      },
    ],
  },
  {
    id: "kha",
    name: "Kha",
    arabic: "خ",
    transliteration: "kh",
    pronunciation: "Like 'ch' in 'Bach' or Scottish 'loch'",
    forms: { isolated: "خ", initial: "خـ", medial: "ـخـ", final: "ـخ" },
    description: "Kha has a dot above. Connects both sides.",
    connection: "both",
    examples: [
      {
        word: "خَرُوف",
        meaning: { en: "Sheep", bs: "Ovca" },
        position: "initial",
      },
      {
        word: "نَخْلَة",
        meaning: { en: "Palm tree", bs: "Palma" },
        position: "medial",
      },
      {
        word: "بِطِّيخ",
        meaning: { en: "Watermelon", bs: "Lubenica" },
        position: "final",
      },
    ],
  },
  {
    id: "dal",
    name: "Dal",
    arabic: "د",
    transliteration: "d",
    pronunciation: "Like 'd' in 'door'",
    forms: { isolated: "د", initial: "د", medial: "ـد", final: "ـد" },
    description: "Dal sounds like D. It connects only to the right.",
    connection: "right",
    examples: [
      {
        word: "دَجَاجَة",
        meaning: { en: "Chicken", bs: "Kokoška" },
        position: "initial",
      },
      {
        word: "مَدْرَسَة",
        meaning: { en: "School", bs: "Škola" },
        position: "medial",
      },
      { word: "يَد", meaning: { en: "Hand", bs: "Ruka" }, position: "final" },
    ],
  },
  {
    id: "dhal",
    name: "Dhal",
    arabic: "ذ",
    transliteration: "dh",
    pronunciation: "Like 'th' in 'this' or 'that'",
    forms: { isolated: "ذ", initial: "ذ", medial: "ـذ", final: "ـذ" },
    description:
      "Dhal sounds like TH (voiced). Dot above. Connects only to the right.",
    connection: "right",
    examples: [
      {
        word: "ذِئْب",
        meaning: { en: "Wolf", bs: "Vuk" },
        position: "initial",
      },
      {
        word: "حِذَاء",
        meaning: { en: "Shoe", bs: "Cipela" },
        position: "medial",
      },
      {
        word: "قُنْفُذ",
        meaning: { en: "Hedgehog", bs: "Jež" },
        position: "final",
      },
    ],
  },
  {
    id: "ra",
    name: "Ra",
    arabic: "ر",
    transliteration: "r",
    pronunciation: "Rolled 'r', like Spanish 'pero'",
    forms: { isolated: "ر", initial: "ر", medial: "ـر", final: "ـر" },
    description: "Ra connects only to the right.",
    connection: "right",
    examples: [
      {
        word: "رَجُل",
        meaning: { en: "Man", bs: "Čovjek" },
        position: "initial",
      },
      {
        word: "كُرْسِيّ",
        meaning: { en: "Chair", bs: "Stolica" },
        position: "medial",
      },
      {
        word: "قَمَر",
        meaning: { en: "Moon", bs: "Mjesec" },
        position: "final",
      },
    ],
  },
  {
    id: "zay",
    name: "Zay",
    arabic: "ز",
    transliteration: "z",
    pronunciation: "Like 'z' in 'zoo'",
    forms: { isolated: "ز", initial: "ز", medial: "ـز", final: "ـز" },
    description:
      "Zay looks like Ra but with a dot above. Connects only to the right.",
    connection: "right",
    examples: [
      {
        word: "زَرَافَة",
        meaning: { en: "Giraffe", bs: "Žirafa" },
        position: "initial",
      },
      {
        word: "مِيزَان",
        meaning: { en: "Scale", bs: "Vaga" },
        position: "medial",
      },
      {
        word: "خُبْز",
        meaning: { en: "Bread", bs: "Hljeb" },
        position: "final",
      },
    ],
  },
  {
    id: "sin",
    name: "Sin",
    arabic: "س",
    transliteration: "s",
    pronunciation: "Like 's' in 'see'",
    forms: { isolated: "س", initial: "سـ", medial: "ـسـ", final: "ـس" },
    description: "Sin has three 'teeth'. Connects both sides.",
    connection: "both",
    examples: [
      {
        word: "سَمَكَة",
        meaning: { en: "Fish", bs: "Riba" },
        position: "initial",
      },
      {
        word: "مَسْجِد",
        meaning: { en: "Mosque", bs: "Džamija" },
        position: "medial",
      },
      { word: "شَمْس", meaning: { en: "Sun", bs: "Sunce" }, position: "final" },
    ],
  },
  {
    id: "shin",
    name: "Shin",
    arabic: "ش",
    transliteration: "sh",
    pronunciation: "Like 'sh' in 'she'",
    forms: { isolated: "ش", initial: "شـ", medial: "ـشـ", final: "ـش" },
    description: "Shin has three dots above. Connects both sides.",
    connection: "both",
    examples: [
      {
        word: "شَمْس",
        meaning: { en: "Sun", bs: "Sunce" },
        position: "initial",
      },
      {
        word: "مِشْمِش",
        meaning: { en: "Apricot", bs: "Kajsija" },
        position: "medial",
      },
      {
        word: "عُشّ",
        meaning: { en: "Nest", bs: "Gnijezdo" },
        position: "final",
      },
    ],
  },
  {
    id: "sad",
    name: "Sad",
    arabic: "ص",
    transliteration: "ṣ",
    pronunciation: "Emphatic 'S'. Deep sound from throat.",
    forms: { isolated: "ص", initial: "صـ", medial: "ـصـ", final: "ـص" },
    description: "Sad has a loop shape. Connects both sides.",
    connection: "both",
    examples: [
      {
        word: "صَقْر",
        meaning: { en: "Falcon", bs: "Sokol" },
        position: "initial",
      },
      {
        word: "عُصْفُور",
        meaning: { en: "Sparrow", bs: "Vrabac" },
        position: "medial",
      },
      {
        word: "مِقَصّ",
        meaning: { en: "Scissors", bs: "Makaze" },
        position: "final",
      },
    ],
  },
  {
    id: "dad",
    name: "Dad",
    arabic: "ض",
    transliteration: "ḍ",
    pronunciation: "Emphatic 'D'. Deep sound.",
    forms: { isolated: "ض", initial: "ضـ", medial: "ـضـ", final: "ـض" },
    description: "Dad is like Sad but with a dot above. Connects both sides.",
    connection: "both",
    examples: [
      {
        word: "ضِفْدَع",
        meaning: { en: "Frog", bs: "Žaba" },
        position: "initial",
      },
      {
        word: "خُضَار",
        meaning: { en: "Vegetables", bs: "Povrće" },
        position: "medial",
      },
      { word: "بَيْض", meaning: { en: "Eggs", bs: "Jaja" }, position: "final" },
    ],
  },
  {
    id: "tah",
    name: "Ta (Emphatic)",
    arabic: "ط",
    transliteration: "ṭ",
    pronunciation: "Emphatic 'T'. Deep sound.",
    forms: { isolated: "ط", initial: "طـ", medial: "ـطـ", final: "ـط" },
    description: "Connects both sides.",
    connection: "both",
    examples: [
      {
        word: "طَائِرَة",
        meaning: { en: "Airplane", bs: "Avion" },
        position: "initial",
      },
      {
        word: "قِطَّة",
        meaning: { en: "Cat", bs: "Mačka" },
        position: "medial",
      },
      { word: "بَطّ", meaning: { en: "Duck", bs: "Patka" }, position: "final" },
    ],
  },
  {
    id: "zah",
    name: "Za (Emphatic)",
    arabic: "ظ",
    transliteration: "ẓ",
    pronunciation: "Emphatic 'TH' (like in 'that'). Deep sound.",
    forms: { isolated: "ظ", initial: "ظـ", medial: "ـظـ", final: "ـظ" },
    description: "Like Ta but with a dot. Connects both sides.",
    connection: "both",
    examples: [
      {
        word: "ظَرْف",
        meaning: { en: "Envelope", bs: "Koverta" },
        position: "initial",
      },
      {
        word: "مِظَلَّة",
        meaning: { en: "Umbrella", bs: "Kišobran" },
        position: "medial",
      },
      {
        word: "حَافِظ",
        meaning: { en: "Protector", bs: "Zaštitnik" },
        position: "final",
      },
    ],
  },
  {
    id: "ayn",
    name: "Ayn",
    arabic: "ع",
    transliteration: "ʿ",
    pronunciation: "Deep throat sound. Constrict throat.",
    forms: { isolated: "ع", initial: "عـ", medial: "ـعـ", final: "ـع" },
    description:
      "Ayn changes shape significantly in the middle/end. Connects both sides.",
    connection: "both",
    examples: [
      {
        word: "عِنَب",
        meaning: { en: "Grapes", bs: "Grožđe" },
        position: "initial",
      },
      {
        word: "ثَعْلَب",
        meaning: { en: "Fox", bs: "Lisica" },
        position: "medial",
      },
      {
        word: "مُرَبَّع",
        meaning: { en: "Square", bs: "Kvadrat" },
        position: "final",
      },
    ],
  },
  {
    id: "ghayn",
    name: "Ghayn",
    arabic: "غ",
    transliteration: "gh",
    pronunciation: "Gargling sound like French 'r'.",
    forms: { isolated: "غ", initial: "غـ", medial: "ـغـ", final: "ـغ" },
    description: "Like Ayn but with a dot above. Connects both sides.",
    connection: "both",
    examples: [
      {
        word: "غَزَال",
        meaning: { en: "Gazelle", bs: "Gazela" },
        position: "initial",
      },
      {
        word: "بَبْغَاء",
        meaning: { en: "Parrot", bs: "Papagaj" },
        position: "medial",
      },
      {
        word: "صَمْغ",
        meaning: { en: "Glue", bs: "Ljepilo" },
        position: "final",
      },
    ],
  },
  {
    id: "fa",
    name: "Fa",
    arabic: "ف",
    transliteration: "f",
    pronunciation: "Like 'f' in 'food'",
    forms: { isolated: "ف", initial: "فـ", medial: "ـفـ", final: "ـف" },
    description: "Fa has one dot above. Connects both sides.",
    connection: "both",
    examples: [
      {
        word: "فِيل",
        meaning: { en: "Elephant", bs: "Slon" },
        position: "initial",
      },
      {
        word: "تُفَّاحَة",
        meaning: { en: "Apple", bs: "Jabuka" },
        position: "medial",
      },
      {
        word: "خَرُوف",
        meaning: { en: "Sheep", bs: "Ovca" },
        position: "final",
      },
    ],
  },
  {
    id: "qaf",
    name: "Qaf",
    arabic: "ق",
    transliteration: "q",
    pronunciation: "Deep 'k' from back of throat.",
    forms: { isolated: "ق", initial: "قـ", medial: "ـقـ", final: "ـق" },
    description: "Qaf has two dots above. Connects both sides.",
    connection: "both",
    examples: [
      {
        word: "قَلَم",
        meaning: { en: "Pen", bs: "Olovka" },
        position: "initial",
      },
      {
        word: "بُرْتُقَال",
        meaning: { en: "Orange", bs: "Narandža" },
        position: "medial",
      },
      {
        word: "طَبَق",
        meaning: { en: "Plate", bs: "Tanjir" },
        position: "final",
      },
    ],
  },
  {
    id: "kaf",
    name: "Kaf",
    arabic: "ك",
    transliteration: "k",
    pronunciation: "Like 'k' in 'keep'",
    forms: { isolated: "ك", initial: "كـ", medial: "ـكـ", final: "ـك" },
    description: "Connects both sides.",
    connection: "both",
    examples: [
      { word: "كَلْب", meaning: { en: "Dog", bs: "Pas" }, position: "initial" },
      {
        word: "سَمَكَة",
        meaning: { en: "Fish", bs: "Riba" },
        position: "medial",
      },
      {
        word: "دِيك",
        meaning: { en: "Rooster", bs: "Pijetao" },
        position: "final",
      },
    ],
  },
  {
    id: "lam",
    name: "Lam",
    arabic: "ل",
    transliteration: "l",
    pronunciation: "Like 'l' in 'look'",
    forms: { isolated: "ل", initial: "لـ", medial: "ـلـ", final: "ـل" },
    description: "Connects both sides.",
    connection: "both",
    examples: [
      {
        word: "لَيْمُون",
        meaning: { en: "Lemon", bs: "Limun" },
        position: "initial",
      },
      {
        word: "عَلَم",
        meaning: { en: "Flag", bs: "Zastava" },
        position: "medial",
      },
      {
        word: "جَمَل",
        meaning: { en: "Camel", bs: "Deva" },
        position: "final",
      },
    ],
  },
  {
    id: "mim",
    name: "Mim",
    arabic: "م",
    transliteration: "m",
    pronunciation: "Like 'm' in 'moon'",
    forms: { isolated: "م", initial: "مـ", medial: "ـمـ", final: "ـم" },
    description: "Connects both sides.",
    connection: "both",
    examples: [
      {
        word: "مَوْز",
        meaning: { en: "Banana", bs: "Banana" },
        position: "initial",
      },
      {
        word: "قَمَر",
        meaning: { en: "Moon", bs: "Mjesec" },
        position: "medial",
      },
      {
        word: "قَلَم",
        meaning: { en: "Pen", bs: "Olovka" },
        position: "final",
      },
    ],
  },
  {
    id: "nun",
    name: "Nun",
    arabic: "ن",
    transliteration: "n",
    pronunciation: "Like 'n' in 'noon'",
    forms: { isolated: "ن", initial: "نـ", medial: "ـنـ", final: "ـn" },
    description: "Dot above. Connects both sides.",
    connection: "both",
    examples: [
      {
        word: "نَمِر",
        meaning: { en: "Tiger", bs: "Tigar" },
        position: "initial",
      },
      {
        word: "عِنَب",
        meaning: { en: "Grapes", bs: "Grožđe" },
        position: "medial",
      },
      { word: "عَيْن", meaning: { en: "Eye", bs: "Oko" }, position: "final" },
    ],
  },
  {
    id: "ha_soft",
    name: "Ha",
    arabic: "ه",
    transliteration: "h",
    pronunciation: "Like 'h' in 'house'",
    forms: { isolated: "ه", initial: "هـ", medial: "ـهـ", final: "ـه" },
    description: "Soft H. Connects both sides. Changes shape in middle/end.",
    connection: "both",
    examples: [
      {
        word: "هَرَم",
        meaning: { en: "Pyramid", bs: "Piramida" },
        position: "initial",
      },
      {
        word: "نَهْر",
        meaning: { en: "River", bs: "Rijeka" },
        position: "medial",
      },
      { word: "وَجْه", meaning: { en: "Face", bs: "Lice" }, position: "final" },
    ],
  },
  {
    id: "waw",
    name: "Waw",
    arabic: "و",
    transliteration: "w",
    pronunciation: "Like 'w' in 'wow'",
    forms: { isolated: "و", initial: "و", medial: "ـو", final: "ـو" },
    description: "Connects only to the right.",
    connection: "right",
    examples: [
      {
        word: "وَرْدَة",
        meaning: { en: "Rose", bs: "Ruža" },
        position: "initial",
      },
      {
        word: "حَوْض",
        meaning: { en: "Basin", bs: "Bazen" },
        position: "medial",
      },
      {
        word: "دَلْو",
        meaning: { en: "Bucket", bs: "Kanta" },
        position: "final",
      },
    ],
  },
  {
    id: "ya",
    name: "Ya",
    arabic: "ي",
    transliteration: "y",
    pronunciation: "Like 'y' in 'yes'",
    forms: { isolated: "ي", initial: "يـ", medial: "ـيـ", final: "ـي" },
    description: "Two dots below. Connects both sides.",
    connection: "both",
    examples: [
      { word: "يَد", meaning: { en: "Hand", bs: "Ruka" }, position: "initial" },
      {
        word: "خِيَار",
        meaning: { en: "Cucumber", bs: "Krastavac" },
        position: "medial",
      },
      {
        word: "كُرْسِيّ",
        meaning: { en: "Chair", bs: "Stolica" },
        position: "final",
      },
    ],
  },
];
